### PR TITLE
DAQ: allsensors code

### PR DESCRIPTION
**Pull request by anaymehta**
# Summary
This code is being written with the express purpose of cleaning and organizing allsensors.ino, which resides in daq->microcontrollers->lexi. This was the code that was intended to be run on the car for competition, and as such it lacks finesse. Our goal is to rewrite this code following OOP principles and class implementations for each of our sensors, make it modular and scalable.

### CODE REVIEW

**Comment by anaymehta** [comment]
## Updates
We're still missing quite a few sensor classes: 

- magnetometer (IMU)
- thermometer (Altimeter)

This is evidenced by their absence in the print_all_sensors() function, which is modeled after test.ino within the daq testing directory. Other missing sensors are outside of our purview (eg. joulemeter) for now.

## Aim

- Implement the missing sensors

**Review by ashvinnagarajan — APPROVED** [review]
Looks great! Approved!

**Comment by anaymehta** [comment]
# Progress Update

- Thermometer, Magnetometer classes created and ready for use.

- Waiting on print_all_sensors() implementation using dictionary to minimize code repetition. Will be completed by @MiraynaMckinney.

- Upon completion, ready to request review, and merge into master.

**Comment by anaymehta** [comment]
Ready for first commit.

**Pull request merged**
