### PR TITLE
LPScript, daqTestingScript finalized

### PR DESCRIPTION
**Pull request by anaymehta**
Just made a few adjustments to the daqTestingScript that I showed you guys last week, so that it is now ready for use as the new and improved LPScript 3.1. The script is dashboard compatible and significantly faster than LPScript 2.3.

### CODE REVIEW

**Comment by anaymehta** [comment]
[daqTestScript --> LPScript_3.1](https://github.com/Bruin-SuperMileage/EV/pull/16/commits/746392ba13ac8e77f41bfbc6039a0d6a3f8d599f) is the primary commit to review, everything else has to do with the daqTestScript and has already been reviewed

**Review by ashvinnagarajan — APPROVED** [review]
It looks like this PR just removes the functionality that prints the millisecond values correct? In that case looks great to me!

**Review by abdullahelqaq — CHANGES_REQUESTED** [review]
My main comments are more about the naming, as opposed to the functionality. 

Not sure how I feel about the naming and directory for `daq/panda/LPScript/LPScript_3.1.py`. What exactly is the purpose of the script? Why does it need its own directory? We can also definitely drop the LP prefix since that's assumed by being under the `panda/` directory. I also am nota huge fan of the versioning in the name.

**Review by abdullahelqaq — COMMENTED** [review]
Yesss looking a lot cleaner. One final nit: is there a reason we need the `main/` directory? If we plan to put other files in there, I'm happy to leave it as is. Otherwise, I'm in favor of removing the directory and having `main.py` live directly under `panda/`

**Review by abdullahelqaq — APPROVED** [review]
Thanks! Looks good!

**Comment by ashvinnagarajan** [comment]
Perhaps even the daqTest directory is unnecessary since its already in the daq folder? @abdullahelqaq I dont mind though

**Comment by abdullahelqaq** [comment]
> Perhaps even the daqTest directory is unnecessary since its already in the daq folder? @abdullahelqaq I dont mind though

That's a good point. I know we keep requesting changes @anaymehta, but do you mind making this last one too?

**Comment by anaymehta** [comment]
> > Perhaps even the daqTest directory is unnecessary since its already in the daq folder? @abdullahelqaq I dont mind though
> 
> That's a good point. I know we keep requesting changes @anaymehta, but do you mind making this last one too?

I can renamed the daqTest directory but I'm not sure about removing the directory, because when I saved the sketch it basically forced me to put it in an eponymous directory. If rename is the decision, any suggestions? Having a test directory within another test directory seems counterintuitive so it'd need to be named something else.

**Comment by abdullahelqaq** [comment]
> > > Perhaps even the daqTest directory is unnecessary since its already in the daq folder? @abdullahelqaq I dont mind though
> > 
> > 
> > That's a good point. I know we keep requesting changes @anaymehta, but do you mind making this last one too?
> 
> I can renamed the daqTest directory but I'm not sure about removing the directory, because when I saved the sketch it basically forced me to put it in an eponymous directory. If rename is the decision, any suggestions? Having a test directory within another test directory seems counterintuitive so it'd need to be named something else.

Hmm I imagine renaming `daqTest.ino` to `test.ino` would resolve a lot of that headache? I'm happy with that existing in `daq/test/test.ino`

**Comment by ashvinnagarajan** [comment]
> > > Perhaps even the daqTest directory is unnecessary since its already in the daq folder? @abdullahelqaq I dont mind though
> > 
> > 
> > That's a good point. I know we keep requesting changes @anaymehta, but do you mind making this last one too?
> 
> I can renamed the daqTest directory but I'm not sure about removing the directory, because when I saved the sketch it basically forced me to put it in an eponymous directory. If rename is the decision, any suggestions? Having a test directory within another test directory seems counterintuitive so it'd need to be named something else.

Oh yeah arduino will force you to make a folder with the same name which is kinda annoying. I agree with abs. Name it `test.ino`

**Comment by anaymehta** [comment]
> > > > Perhaps even the daqTest directory is unnecessary since its already in the daq folder? @abdullahelqaq I dont mind though
> > > 
> > > 
> > > That's a good point. I know we keep requesting changes @anaymehta, but do you mind making this last one too?
> > 
> > 
> > I can renamed the daqTest directory but I'm not sure about removing the directory, because when I saved the sketch it basically forced me to put it in an eponymous directory. If rename is the decision, any suggestions? Having a test directory within another test directory seems counterintuitive so it'd need to be named something else.
> 
> Oh yeah arduino will force you to make a folder with the same name which is kinda annoying. I agree with abs. Name it `test.ino`

consider it done!

**Comment by ashvinnagarajan** [comment]
Well actually that would mean we could only ever have one test script. Maybe its better to just leave it as is?

**Comment by abdullahelqaq** [comment]
> Well actually that would mean we could only ever have one test script. Maybe its better to just leave it as is?

I'm happy with having a single test script that runs multiple routines from the directory. Might be the best compromise here haha

**Comment by anaymehta** [comment]
All good now?

**Comment by ashvinnagarajan** [comment]
Great lets do it! Go ahead and merge this PR!

**Comment by anaymehta** [comment]
Hype hype hype we merged!

**Pull request merged**
